name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create tarball directly from git commit (no file-change errors)
      - name: Create deploy tarball
        run: |
          git archive --format=tar.gz -o app.tar.gz HEAD

      - name: Upload tarball to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "/home/azureuser/"

      - name: Deploy & start app on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            APP_DIR="/home/azureuser/hello-api"
            TAR_PATH="/home/azureuser/app.tar.gz"

            echo "==> Preparing app dir"
            mkdir -p "$APP_DIR"

            echo "==> Extracting tarball into $APP_DIR"
            tar -xzf "$TAR_PATH" -C "$APP_DIR"
            rm -f "$TAR_PATH"
