name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Copy repo to VM (no git pull on VM)
      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # uncomment next line ONLY if your .pem has a passphrase
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH || '/opt/hello-api' }}
          rm: true
          strip_components: 0
          overwrite: true

      # 2) Setup runtime and (re)start app on port 80
      - name: Configure and start service on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            # Node & PM2
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            sudo npm i -g pm2

            APP_DIR="${DEPLOY_PATH:-/opt/hello-api}"
            sudo mkdir -p "$APP_DIR"
            sudo chown -R $USER:$USER "$APP_DIR"
            cd "$APP_DIR"

            # optional cleanup if you dislike CI files on the VM
            rm -rf .git || true

            # install deps
            if [ -f package-lock.json ]; then
              npm ci --omit=dev
            else
              npm install --omit=dev
            fi

            # allow binding to port 80
            NODE_BIN=$(readlink -f "$(which node)")
            sudo setcap 'cap_net_bind_service=+ep' "$NODE_BIN" || true

            # start/restart via PM2
            if pm2 list | grep -q "hello-api"; then
              pm2 restart hello-api
            else
              pm2 start npm --name "hello-api" -- start
            fi
            pm2 save

            # autostart on reboot
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp $HOME -y >/dev/null 2>&1 || true

            # open port 80 if ufw is active
            if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q active; then
              sudo ufw allow 80/tcp || true
            fi
