name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Copy repo contents to VM (flatten to target)
      - name: Copy files to VM (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH || '/opt/hello-api' }}
          rm: true
          strip_components: 1
          overwrite: true

      # 3) Install Node.js and start app
      - name: Configure and start service on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            APP_DIR="${DEPLOY_PATH:-/opt/hello-api}"
            sudo mkdir -p "$APP_DIR"
            sudo chown -R $USER:$USER "$APP_DIR"

            echo "==> Listing files after copy"
            ls -la "$APP_DIR"

            if [ ! -f "$APP_DIR/package.json" ]; then
              echo "ERROR: package.json not found in $APP_DIR"
              exit 1
            fi

            # Install Node.js if missing
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install pm2 if missing
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi

            cd "$APP_DIR"

            echo "==> Installing dependencies"
            npm install --omit=dev

            NODE_BIN=$(readlink -f "$(which node)")
            sudo setcap 'cap_net_bind_service=+ep' "$NODE_BIN" || true

            echo "==> Starting app with PM2"
            if pm2 list | grep -q "hello-api"; then
              pm2 restart hello-api
            else
              pm2 start npm --name "hello-api" -- start
            fi
            pm2 save

            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp $HOME -y >/dev/null 2>&1 || true

            if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q active; then
              sudo ufw allow 80/tcp || true
            fi
